### ISSUE TITLE
Eth sign and personal sign

### ISSUE THREAD

**Issue by dekz** [trufflesuite/truffle-hdwallet-provider#21]
Hey There,

It looks like this provider only supports `signTransaction` but not `signMessage` aka `eth_sign` and `personal_sign`, see [here](https://github.com/MetaMask/provider-engine/blob/master/subproviders/hooked-wallet.js#L275) and [here](https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_sign). 

Any chance that you could add support for this?

**Comment by mattkanwisher** [comment]
running into same issue here also

**Comment by dekz** [comment]
@mattkanwisher we ended up writing our own Mnemonic and PrivateKey subproviders (to be used in conjunction with Web3ProviderEngine). It will probably help you out, check it out [here](https://github.com/0xProject/0x-monorepo/blob/development/packages/subproviders/src/index.ts#L29).

**Comment by benjamincburns** [comment]
fixed by #67
