### ISSUE TITLE
How to use truffle-hdwallet-provider with ethereumjs-tx?

### ISSUE THREAD

**Issue by shumail92** [trufflesuite/truffle-hdwallet-provider#73]
I am wondering how can I use it to sign transactions with ethereumjs-tx? 
The `sign()` method of ethereumjs-tx accepts private key `Buffer` as mentioned in docs:
https://github.com/ethereumjs/ethereumjs-tx/blob/master/docs/index.md#sign

How can I use truffle-hdwallet-provider to sign the transaction?

**Comment by gnidan** [comment]
Hi, could you please re-open this issue in [trufflesuite/truffle](https://github.com/trufflesuite/truffle/issues/new)? Looking to archive this repo, as this package is now in the monorepo.

**Comment by shumail92** [comment]
Sure.

**Comment by shumail92** [comment]
Opened @ https://github.com/trufflesuite/truffle/issues/1381
