### ISSUE TITLE
Publish private-key changes

### ISSUE THREAD

**Issue by slyfox42** [trufflesuite/truffle-hdwallet-provider#80]
Hi guys, I stumbled upon this package 1 month ago when writing a CLI tool for contract deployment. The source code has the logic to accept a private key rather than a mnemonic, while neither the latest version 0.0.6 nor beta-0.0.7 have it. 

Is there any ETA on when these changes will be published to NPM? 

Thanks!

**Comment by D-Nice** [comment]
It's already published, try with @beta dist-tag when downloading:

`pnpm i truffle-hdwallet-provider@beta`

**Comment by slyfox42** [comment]
@D-Nice thanks a lot!
