### ISSUE TITLE
Version 1.0.8 breaks installation.

### ISSUE THREAD

**Issue by caleteeter** [trufflesuite/truffle-hdwallet-provider#99]
OS Version: Windows 10 18.09
Truffle Version: v5.0.17
Solidity Version: v0.5.0
Node Version: v10.15.3
Web3js Version: v1.0.0-beta.37
Truffle HD Wallet Provider Version: 1.0.8

When using v1.0.7 or earlier, there is no issue adding the hnpm install
npm WARN deprecated fs-promise@2.0.3: Use mz or fs-extra^3.0 with Promise Support
npm WARN deprecated tar.gz@1.0.7: ⚠️  WARNING ⚠️ tar.gz module has been deprecated and your application is vulnerable. Please use tar module inst
ead: https://npmjs.com/tar
npm WARN TruffleWalletTest@1.0.0 No description
npm WARN TruffleWalletTest@1.0.0 No repository field.

npm ERR! path C:\Users\caleteet\Source\Test\TruffleWalletTest\node_modules\buffer-fill\package.json.478327879
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall rename
npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\caleteet\Source\Test\TruffleWalletTest\node_modules\buffer-fill\package.json.478327879' -> 'C:\Users\caleteet\Source\Test\TruffleWalletTest\node_modules\buffer-fill\package.json'
npm ERR!  { [Error: EPERM: operation not permitted, rename 'C:\Users\caleteet\Source\Test\TruffleWalletTest\node_modules\buffer-fill\package.json.478327879' -> 'C:\Users\caleteet\Source\Test\TruffleWalletTest\node_modules\buffer-fill\package.json']
npm ERR!   cause:
npm ERR!    { Error: EPERM: operation not permitted, rename 'C:\Users\caleteet\Source\Test\TruffleWalletTest\node_modules\buffer-fill\package.json.478327879' -> 'C:\Users\caleteet\Source\Test\TruffleWalletTest\node_modules\buffer-fill\package.json'
npm ERR!      errno: -4048,
npm ERR!      code: 'EPERM',
npm ERR!      syscall: 'rename',
npm ERR!      path:
npm ERR!       'C:\\Users\\caleteet\\Source\\Test\\TruffleWalletTest\\node_modules\\buffer-fill\\package.json.478327879',
npm ERR!      dest:
npm ERR!       'C:\\Users\\caleteet\\Source\\Test\\TruffleWalletTest\\node_modules\\buffer-fill\\package.json' },
npm ERR!   stack:
npm ERR!    'Error: EPERM: operation not permitted, rename \'C:\\Users\\caleteet\\Source\\Test\\TruffleWalletTest\\node_modules\\buffer-fill\\package.json.478327879\' -> \'C:\\Users\\caleteet\\Source\\Test\\TruffleWalletTest\\node_modules\\buffer-fill\\package.json\'',
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'rename',
npm ERR!   path:
npm ERR!    'C:\\Users\\caleteet\\Source\\Test\\TruffleWalletTest\\node_modules\\buffer-fill\\package.json.478327879',
npm ERR!   dest:
npm ERR!    'C:\\Users\\caleteet\\Source\\Test\\TruffleWalletTest\\node_modules\\buffer-fill\\package.json',
npm ERR!   parent: 'TruffleWalletTest' }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It's possible that the file was already in use (by a text editor or antivirus),
npm ERR! or that you lack permissions to access it.
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).d wallet provider to the truffle configuration and restoring the npm packages.  When running with v1.0.8, there is an exception.

``

**Comment by AlexZhu2** [comment]
Hi there! I encountered the same problem. Have you solved the problem.

**Comment by johnsonchenchina** [comment]
npm -g truffle-hdwallet-provider --unsafe-perm

**Comment by caleteeter** [comment]
This is resolved for me in v1.0.10
